---
  root: true
  env:
    browser: true
    es6: true
  extends:
    - "eslint:recommended"
    - "plugin:react/recommended"
    - "plugin:import/errors"
    - "plugin:import/warnings"
    - "prettier"
  parserOptions:
    ecmaFeatures:
      jsx: true
    ecmaVersion: 2018
    sourceType: "module"
  settings:
    react:
      version: "detect"
